In [1]:
print("Hello, Canadian Bank SQL Analysis!")

Hello, Canadian Bank SQL Analysis!

In [5]:
import yfinance as yf
import pandas as pd

banks = ["RY.TO", "TD.TO", "BMO.TO", "BNS.TO", "CM.TO"]

data = yf.download(
    banks, start="2016-01-01", 
    end="2026-01-01", 
    auto_adjust=False
)

data.head()

[*********************100%***********************]  5 of 5 completed

Price       Adj Close                                                  Close  \
Ticker         BMO.TO     BNS.TO      CM.TO      RY.TO      TD.TO     BMO.TO
Date
2016-01-04  48.961098  32.410679  27.465481  48.578289  34.578743  76.660004
2016-01-05  48.935535  32.754978  27.513390  48.431973  34.443573  76.620003
2016-01-06  47.849777  32.188931  27.333717  47.600590  33.910664  74.919998
2016-01-07  46.955635  31.692902  26.854593  46.722668  33.163300  73.519997
2016-01-08  46.955635  31.838789  26.692898  46.602970  33.176300  73.519997

Price                                                   ...       Open  \
Ticker         BNS.TO      CM.TO      RY.TO      TD.TO  ...     BMO.TO
Date                                                    ...
2016-01-04  55.540001  45.860001  73.040001  53.720001  ...  76.820000
2016-01-05  56.130001  45.939999  72.820000  53.509998  ...  76.669998
2016-01-06  55.160000  45.639999  71.570000  52.180000  ...  76.000000
2016-01-07  54.310001  44.840000  70.250000  51.029999  ...  73.779999
2016-01-08  54.560001  44.570000  70.070000  51.049999  ...  74.300003

Price                                                    Volume           \
Ticker         BNS.TO      CM.TO      RY.TO      TD.TO   BMO.TO   BNS.TO
Date
2016-01-04  55.250000  45.174999  73.269997  53.689999  1755800  2979400
2016-01-05  55.610001  45.794998  73.209999  53.750000  1324200  2374500
2016-01-06  55.669998  45.500000  72.250000  52.810001  1913800  2446800
2016-01-07  54.500000  45.005001  70.500000  51.369999  2246600  2530800
2016-01-08  55.169998  45.060001  71.000000  51.750000  1413400  2003500

Price
Ticker        CM.TO    RY.TO    TD.TO
Date
2016-01-04  3039400  2359600  3213900
2016-01-05  2346800  2277400  3555200
2016-01-06  2009000  2894900  3564100
2016-01-07  4199200  3636500  3820600
2016-01-08  3368600  2616800  2959600

[5 rows x 30 columns]

In [6]:
banks

['RY.TO', 'TD.TO', 'BMO.TO', 'BNS.TO', 'CM.TO']

In [7]:
data.columns

MultiIndex([('Adj Close', 'BMO.TO'),
            ('Adj Close', 'BNS.TO'),
            ('Adj Close',  'CM.TO'),
            ('Adj Close',  'RY.TO'),
            ('Adj Close',  'TD.TO'),
            (    'Close', 'BMO.TO'),
            (    'Close', 'BNS.TO'),
            (    'Close',  'CM.TO'),
            (    'Close',  'RY.TO'),
            (    'Close',  'TD.TO'),
            (     'High', 'BMO.TO'),
            (     'High', 'BNS.TO'),
            (     'High',  'CM.TO'),
            (     'High',  'RY.TO'),
            (     'High',  'TD.TO'),
            (      'Low', 'BMO.TO'),
            (      'Low', 'BNS.TO'),
            (      'Low',  'CM.TO'),
            (      'Low',  'RY.TO'),
            (      'Low',  'TD.TO'),
            (     'Open', 'BMO.TO'),
            (     'Open', 'BNS.TO'),
            (     'Open',  'CM.TO'),
            (     'Open',  'RY.TO'),
            (     'Open',  'TD.TO'),
            (   'Volume', 'BMO.TO'),
            (   'Volume', 'BNS.TO'),
            (   'Volume',  'CM.TO'),
            (   'Volume',  'RY.TO'),
            (   'Volume',  'TD.TO')],
           names=['Price', 'Ticker'])

In [8]:
df = data.stack(level="Ticker", future_stack=True). reset_index()

df.head()

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume
0,2016-01-04,BMO.TO,48.961098,76.660004,76.989998,76.040001,76.820000,1755800
1,2016-01-04,BNS.TO,32.410679,55.540001,55.689999,54.750000,55.250000,2979400
2,2016-01-04,CM.TO,27.465481,45.860001,45.915001,44.650002,45.174999,3039400
3,2016-01-04,RY.TO,48.578289,73.040001,73.269997,72.050003,73.269997,2359600
4,2016-01-04,TD.TO,34.578743,53.720001,53.759998,53.029999,53.689999,3213900

In [9]:
df.to_csv("bank_stock_data.csv", index=False)

print("CSV saved successfully")

CSV saved successfully

In [10]:
import sqlite3
import pandas as pd

df = pd.read_csv("bank_stock_data.csv")

conn = sqlite3.connect("bank_stock.db")

df.to_sql("stock_prices", conn, if_exists="replace", index=False)

conn.close()

print("Database created successfully!")

Database created successfully!

In [12]:
import sqlite3

conn = sqlite3.connect("bank_stock.db")

result = pd.read_sql("SELECT * FROM stock_prices LIMIT 5", conn)

result

,Date,Ticker,Adj Close,Close,High,Low,Open,Volume
0,2016-01-04,BMO.TO,48.961098,76.660004,76.989998,76.040001,76.820000,1755800
1,2016-01-04,BNS.TO,32.410679,55.540001,55.689999,54.750000,55.250000,2979400
2,2016-01-04,CM.TO,27.465481,45.860001,45.915001,44.650002,45.174999,3039400
3,2016-01-04,RY.TO,48.578289,73.040001,73.269997,72.050003,73.269997,2359600
4,2016-01-04,TD.TO,34.578743,53.720001,53.759998,53.029999,53.689999,3213900

In [14]:
query = """
SELECT COUNT(*) AS total_rows
FROM stock_prices;
"""

pd.read_sql(query, conn)

   total_rows
0       12545

In [16]:
query = """SELECT DISTINCT Ticker FROM stock_prices;"""

pd.read_sql(query, conn)

   Ticker
0  BMO.TO
1  BNS.TO
2   CM.TO
3   RY.TO
4   TD.TO

In [17]:
query = """ SELECT Ticker, COUNT(*) AS number_of_rows 
FROM stock_prices 
GROUP BY Ticker; """

pd.read_sql(query, conn)

   Ticker  number_of_rows
0  BMO.TO            2509
1  BNS.TO            2509
2   CM.TO            2509
3   RY.TO            2509
4   TD.TO            2509

In [18]:
query = """ SELECT MIN(Date) AS first_date, MAX(Date) AS last_date
FROM stock_prices;"""

pd.read_sql(query, conn)

   first_date   last_date
0  2016-01-04  2025-12-31

In [21]:
query = """ SELECT Ticker, ROUND(AVG(CLOSE), 2) AS avg_close
FROM stock_prices
GROUP BY Ticker
ORDER BY avg_close DESC;"""

pd.read_sql(query, conn)

   Ticker  avg_close
0   RY.TO     119.22
1  BMO.TO     111.63
2   TD.TO      77.60
3  BNS.TO      72.36
4   CM.TO      63.21

In [22]:
query = """SELECT Ticker, 
ROUND(MAX(Close), 2) AS highest_close
FROM stock_prices
GROUP BY Ticker
ORDER BY highest_close DESC;"""
pd.read_sql(query, conn)

   Ticker  highest_close
0   RY.TO         235.18
1  BMO.TO         182.00
2   TD.TO         129.81
3   CM.TO         128.38
4  BNS.TO         101.33

In [24]:
query = """ SELECT Ticker, 
ROUND(MIN(Close), 2) AS lowest_close
FROM stock_prices
GROUP BY Ticker
ORDER BY lowest_close DESC;"""
pd.read_sql(query, conn)

   Ticker  lowest_close
0   RY.TO         65.00
1  BMO.TO         56.24
2   TD.TO         49.02
3  BNS.TO         46.72
4   CM.TO         33.81

In [25]:
query = """ SELECT Ticker, 
SUBSTR(Date, 1, 4) AS Year, 
ROUND(AVG(Close), 2) AS ave_close
FROM stock_prices
GROUP BY Ticker, Year
ORDER BY Year, Ticker;"""
pd.read_sql(query, conn)

    Ticker  Year  ave_close
0   BMO.TO  2016      82.58
1   BNS.TO  2016      65.35
2    CM.TO  2016      49.57
3    RY.TO  2016      78.77
4    TD.TO  2016      57.10
5   BMO.TO  2017      96.90
6   BNS.TO  2017      78.94
7    CM.TO  2017      55.81
8    RY.TO  2017      96.10
9    TD.TO  2017      67.71
10  BMO.TO  2018     100.44
11  BNS.TO  2018      76.36
12   CM.TO  2018      58.06
13   RY.TO  2018     100.04
14   TD.TO  2018      74.48
15  BMO.TO  2019      99.08
16  BNS.TO  2019      72.57
17   CM.TO  2019      54.18
18   RY.TO  2019     103.66
19   TD.TO  2019      74.69
20  BMO.TO  2020      81.93
21  BNS.TO  2020      60.16
22   CM.TO  2020      48.72
23   RY.TO  2020      96.05
24   TD.TO  2020      63.95
25  BMO.TO  2021     121.86
26  BNS.TO  2021      78.71
27   CM.TO  2021      67.94
28   RY.TO  2021     122.82
29   TD.TO  2021      84.77
30  BMO.TO  2022     133.62
31  BNS.TO  2022      79.07
32   CM.TO  2022      68.27
33   RY.TO  2022     131.53
34   TD.TO  2022      91.76
35  BMO.TO  2023     119.55
36  BNS.TO  2023      65.04
37   CM.TO  2023      56.43
38   RY.TO  2023     126.64
39   TD.TO  2023      83.33
40  BMO.TO  2024     125.05
41  BNS.TO  2024      67.82
42   CM.TO  2024      73.26
43   RY.TO  2024     150.88
44   TD.TO  2024      79.49
45  BMO.TO  2025     155.40
46  BNS.TO  2025      79.70
47   CM.TO  2025      99.87
48   RY.TO  2025     185.69
49   TD.TO  2025      98.81

In [30]:
query = """
SELECT Ticker, Date, Close FROM stock_prices 
WHERE (Ticker, Close) IN (
SELECT Ticker, MAX(Close) FROM stock_prices
GROUP BY Ticker
)
ORDER BY Ticker;"""
pd.read_sql(query, conn)

   Ticker        Date       Close
0  BMO.TO  2025-09-26  182.000000
1  BNS.TO  2025-12-30  101.330002
2   CM.TO  2025-12-15  128.380005
3   RY.TO  2025-12-29  235.179993
4   TD.TO  2025-12-30  129.809998

In [33]:
query = """SELECT Ticker, ROUND(AVG(Volume), 0) AS avg_volume
FROM stock_prices
GROUP BY Ticker
ORDER BY avg_volume DESC;"""
pd.read_sql(query, conn)

   Ticker  avg_volume
0   TD.TO   5038656.0
1  BNS.TO   3531460.0
2   RY.TO   3489863.0
3   CM.TO   3308419.0
4  BMO.TO   2141928.0

In [39]:
query = """
WITH first_prices AS (
    SELECT Ticker, Close
    FROM stock_prices
    WHERE Date = '2016-01-04'),
last_prices AS (
    SELECT Ticker, Close
    FROM stock_prices
    WHERE Date = '2025-12-31')
SELECT 
    f.Ticker,
    ROUND(f.Close, 2) AS start_price,
    ROUND(l.Close, 2) AS end_price,
    ROUND((l.Close - f.Close) / f.Close * 100, 2) AS return_pct
FROM first_prices f
JOIN last_prices l
ON f.Ticker = l.Ticker
ORDER BY return_pct DESC;
"""

pd.read_sql(query, conn)

   Ticker  start_price  end_price  return_pct
0   RY.TO        73.04     233.99      220.36
1   CM.TO        45.86     124.43      171.33
2   TD.TO        53.72     129.36      140.80
3  BMO.TO        76.66     178.25      132.52
4  BNS.TO        55.54     101.23       82.27

In [42]:
query = """
WITH yearly_prices AS (
    SELECT
        Ticker,
        SUBSTR(Date, 1, 4) AS Year,
        FIRST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
        ) AS start_price,
        LAST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS end_price
    FROM stock_prices
)
SELECT DISTINCT
    Ticker,
    Year,
    ROUND((end_price - start_price) / start_price * 100, 2) AS annual_return_pct
FROM yearly_prices
ORDER BY Year, Ticker;
"""

pd.read_sql(query, conn)

    Ticker  Year  annual_return_pct
0   BMO.TO  2016              25.97
1   BNS.TO  2016              34.61
2    CM.TO  2016              19.45
3    RY.TO  2016              24.41
4    TD.TO  2016              23.27
5   BMO.TO  2017               3.64
6   BNS.TO  2017               7.07
7    CM.TO  2017              10.56
8    RY.TO  2017              12.19
9    TD.TO  2017              10.07
10  BMO.TO  2018             -11.13
11  BNS.TO  2018             -16.48
12   CM.TO  2018             -16.93
13   RY.TO  2018              -9.24
14   TD.TO  2018              -7.94
15  BMO.TO  2019              12.37
16  BNS.TO  2019               7.44
17   CM.TO  2019               5.63
18   RY.TO  2019               9.75
19   TD.TO  2019               6.71
20  BMO.TO  2020              -4.04
21  BNS.TO  2020              -6.60
22   CM.TO  2020               0.45
23   RY.TO  2020               1.00
24   TD.TO  2020              -2.04
25  BMO.TO  2021              41.88
26  BNS.TO  2021              32.24
27   CM.TO  2021              36.50
28   RY.TO  2021              28.25
29   TD.TO  2021              34.81
30  BMO.TO  2022             -13.05
31  BNS.TO  2022             -26.98
32   CM.TO  2022             -26.79
33   RY.TO  2022              -6.97
34   TD.TO  2022             -11.76
35  BMO.TO  2023               5.34
36  BNS.TO  2023              -1.06
37   CM.TO  2023              15.16
38   RY.TO  2023               4.66
39   TD.TO  2023              -2.34
40  BMO.TO  2024               6.94
41  BNS.TO  2024              21.89
42   CM.TO  2024              42.59
43   RY.TO  2024              29.39
44   TD.TO  2024             -10.69
45  BMO.TO  2025              27.51
46  BNS.TO  2025              31.04
47   CM.TO  2025              37.61
48   RY.TO  2025              35.83
49   TD.TO  2025              69.10

In [43]:
query = """
WITH yearly_returns AS (
    SELECT
        Ticker,
        SUBSTR(Date, 1, 4) AS Year,
        FIRST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
        ) AS start_price,
        LAST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS end_price
    FROM stock_prices
),
annual_returns AS (
    SELECT DISTINCT
        Ticker,
        Year,
        (end_price - start_price) / start_price * 100 AS return_pct
    FROM yearly_returns
)
SELECT
    Ticker,
    Year,
    ROUND(return_pct, 2) AS best_return_pct
FROM annual_returns a
WHERE return_pct = (
    SELECT MAX(return_pct)
    FROM annual_returns b
    WHERE b.Ticker = a.Ticker
)
ORDER BY best_return_pct DESC;
"""

pd.read_sql(query, conn)

   Ticker  Year  best_return_pct
0   TD.TO  2025            69.10
1   CM.TO  2024            42.59
2  BMO.TO  2021            41.88
3   RY.TO  2025            35.83
4  BNS.TO  2016            34.61

In [48]:
query = """
WITH yearly_returns AS (
    SELECT
        Ticker,
        SUBSTR(Date, 1, 4) AS Year,
        FIRST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
        ) AS start_price,
        LAST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS end_price
    FROM stock_prices
),
annual_returns AS (
    SELECT DISTINCT
        Ticker,
        Year,
        (end_price - start_price) / start_price * 100 AS return_pct
    FROM yearly_returns
)
SELECT
    Ticker,
    Year,
    ROUND(return_pct, 2) AS worst_return_pct
FROM annual_returns a
WHERE return_pct = (
    SELECT MIN(return_pct)
    FROM annual_returns b
    WHERE b.Ticker = a.Ticker
)
ORDER BY worst_return_pct ASC;
"""

pd.read_sql(query, conn)

   Ticker  Year  worst_return_pct
0  BNS.TO  2022            -26.98
1   CM.TO  2022            -26.79
2  BMO.TO  2022            -13.05
3   TD.TO  2022            -11.76
4   RY.TO  2018             -9.24

In [51]:
query = """
WITH yearly_returns AS (
    SELECT
        Ticker,
        SUBSTR(Date, 1, 4) AS Year,
        FIRST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
        ) AS start_price,
        LAST_VALUE(Close) OVER (
            PARTITION BY Ticker, SUBSTR(Date, 1, 4)
            ORDER BY Date
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS end_price
    FROM stock_prices
),
annual_returns AS (
    SELECT DISTINCT
        Ticker,
        Year,
        (end_price - start_price) / start_price * 100 AS return_pct
    FROM yearly_returns
)
SELECT
    Ticker,
    ROUND(AVG(return_pct), 2) AS avg_annual_return_pct
FROM annual_returns
GROUP BY Ticker
ORDER BY avg_annual_return_pct DESC;
"""

pd.read_sql(query, conn)

   Ticker  avg_annual_return_pct
0   RY.TO                  12.93
1   CM.TO                  12.42
2   TD.TO                  10.92
3  BMO.TO                   9.54
4  BNS.TO                   8.32